version: "3.8"  # Updated version for newer features
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3300:3306"  # Exposing default MySQL port
    environment:
      - MYSQL_ROOT_PASSWORD=787898  # Matches your Dockerfile ENV
      - MYSQL_DATABASE=smile_classifier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  app:
    build:
      context: .  # Build context points to current directory
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Matches Uvicorn's default port
    environment:  # Pass environment variables to app
      - MYSQL_HOST=mysql_container
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=787898
      - MYSQL_DB=smile_classifier
    depends_on:
      db:
        condition: service_healthy  # Ensures the app waits for  the database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
